name: nk_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  shared_preferences: ^2.3.2
  fluttertoast: ^8.2.8
  http: ^1.2.2
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.1
  flutter_app_badger: ^1.5.0
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/nk_logo.png
    - assets/icon/nk_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/nk_icon.png"

flutter_native_splash:
  color: "#004a99" 
  image: assets/icon/nk_icon.png  
  android: true
  ios: true
  web: false