// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpjo1udXBm2nbZmOJkCB8eQAjLt5HX7r8',
    appId: '1:922670014152:web:842adda819dc2b71e40ffd',
    messagingSenderId: '922670014152',
    projectId: 'nk-push-app-dev',
    authDomain: 'nk-push-app-dev.firebaseapp.com',
    storageBucket: 'nk-push-app-dev.appspot.com',
    measurementId: 'G-R23KB554X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC2QUbhJSPFyMCskEckigvqAf3D379Pbk',
    appId: '1:922670014152:android:77478ad6742a2872e40ffd',
    messagingSenderId: '922670014152',
    projectId: 'nk-push-app-dev',
    storageBucket: 'nk-push-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1IBJCUyfqeLGjY2TMYeX5OAaDFi_UY34',
    appId: '1:922670014152:ios:0accad97d6085a3fe40ffd',
    messagingSenderId: '922670014152',
    projectId: 'nk-push-app-dev',
    storageBucket: 'nk-push-app-dev.appspot.com',
    iosBundleId: 'com.example.nkApp',
  );
}
